[versions]
##########################################################################
# Plugins
# Check this on https://kotlinlang.org/docs/releases.html
kotlin = "2.3.0"
##########################################################################
# Java Configuration
# The Java version the JDK will be for compiling and running code.
java = "25"
# The Java version the JDK will be for running Gradle.
gradleJava = "25"
##########################################################################
# Dependencies
# Check this on https://github.com/JetBrains/compose-jb/releases/latest/
compose = "1.10.0"
# Check this on https://github.com/Kotlin/kotlinx.coroutines/releases/latest/
coroutines = "1.10.2"
# Check this on https://central.sonatype.com/artifact/org.jetbrains.compose.material3/material3-desktop/
materialDesktop = "1.10.0-alpha05"
##########################################################################

[libraries]
coroutines = { group = "org.jetbrains.kotlinx", name = "kotlinx-coroutines-core", version.ref = "coroutines" }
materialDesktop = { group = "org.jetbrains.compose.material3", name = "material3-desktop", version.ref = "materialDesktop" }

[plugins]
kotlin-jvm = { id = "org.jetbrains.kotlin.jvm", version.ref = "kotlin" }
compose = { id = "org.jetbrains.compose", version.ref = "compose" }
kotlin-plugin-compose = { id = "org.jetbrains.kotlin.plugin.compose", version.ref = "kotlin" }